// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT token, created_at, updated_at, user_id, hashed_token, expires_at, revoked_at FROM refresh_tokens
WHERE hashed_token = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, hashedToken string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByHash, hashedToken)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.HashedToken,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllExpiredRefreshToken = `-- name: RevokeAllExpiredRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW(), updated_at = NOW()
WHERE expires_at < NOW()
`

func (q *Queries) RevokeAllExpiredRefreshToken(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, revokeAllExpiredRefreshToken)
	return err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked_at = NOW(), updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}

const revokeRefreshTokenByToken = `-- name: RevokeRefreshTokenByToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW(), updated_at = NOW()
WHERE hashed_token = $1
`

func (q *Queries) RevokeRefreshTokenByToken(ctx context.Context, hashedToken string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenByToken, hashedToken)
	return err
}

const setRefreshTokenInvalid = `-- name: SetRefreshTokenInvalid :exec
UPDATE refresh_tokens
SET revoked_at = NOW(), updated_at = NOW()
WHERE token = $1
`

func (q *Queries) SetRefreshTokenInvalid(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, setRefreshTokenInvalid, token)
	return err
}

const storeRefreshToken = `-- name: StoreRefreshToken :one
INSERT INTO refresh_tokens(token, created_at, updated_at, hashed_token,user_id, expires_at)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING token, created_at, updated_at, user_id, hashed_token, expires_at, revoked_at
`

type StoreRefreshTokenParams struct {
	HashedToken string
	UserID      uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, storeRefreshToken, arg.HashedToken, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.HashedToken,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
