// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_id.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSessionIDByID = `-- name: GetSessionIDByID :one
SELECT id, created_at, updated_at, user_id, expires_at, revoked_at FROM session_ids
WHERE id = $1
`

func (q *Queries) GetSessionIDByID(ctx context.Context, id string) (SessionID, error) {
	row := q.db.QueryRowContext(ctx, getSessionIDByID, id)
	var i SessionID
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllExpiredSessionIDs = `-- name: RevokeAllExpiredSessionIDs :exec
UPDATE session_ids
SET revoked_at = NOW(), updated_at = NOW()
WHERE expires_at < NOW()
`

func (q *Queries) RevokeAllExpiredSessionIDs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, revokeAllExpiredSessionIDs)
	return err
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
UPDATE session_ids
SET revoked_at = NOW(), updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllSessionsForUser, userID)
	return err
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE session_ids
SET revoked_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeSessionByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeSessionByID, id)
	return err
}

const setSessionIDInvalid = `-- name: SetSessionIDInvalid :exec
UPDATE session_ids
SET revoked_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SetSessionIDInvalid(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setSessionIDInvalid, id)
	return err
}

const storeSessionID = `-- name: StoreSessionID :one
INSERT INTO session_ids(id, created_at, updated_at, user_id, expires_at)
VALUES(
    $1,
    NOW(),
    NOW(),
    $2,
    $3
)
RETURNING id, created_at, updated_at, user_id, expires_at, revoked_at
`

type StoreSessionIDParams struct {
	ID        string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) StoreSessionID(ctx context.Context, arg StoreSessionIDParams) (SessionID, error) {
	row := q.db.QueryRowContext(ctx, storeSessionID, arg.ID, arg.UserID, arg.ExpiresAt)
	var i SessionID
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
