@baseUrl = http://localhost:8080

### Create user 1
# @name createUser1
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "email": "mloneusk@example.co"
}


### Create user 2
# @name createUser2
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "email": "johny@mail.dev"
}


### Create user 3
# @name createUser3
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "email": "dackjorsey@example.co"
}


### Create chirp (using user_id from response)
POST {{baseUrl}}/api/chirps
Content-Type: application/json

{
  "body": "This is just a chirp",
  "user_id": "{{createUser1.response.body.id}}"
}

###
# @name chirp1
POST {{baseUrl}}/api/chirps
Content-Type: application/json

{
  "body": "'This is just a chirp', haha such a Kerfuffle !",
  "user_id": "{{createUser2.response.body.id}}"
}

###
# @name chirp2
POST {{baseUrl}}/api/chirps
Content-Type: application/json

{
  "body": "Shipping on Friday was a mistake.",
  "user_id": "{{createUser3.response.body.id}}"
}

### Get all chirps
GET {{baseUrl}}/api/chirps
Accept: application/json

### Get one chirp
GET {{baseUrl}}/api/chirps/{{chirp1.response.body.id}}
Accept: application/json

### Get one chirp
#d6a88b7c-ea38-4aae-88be-07df36c03dd0
GET {{baseUrl}}/api/chirps/{{chirp2.response.body.id}}
Accept: application/json