@baseUrl = http://localhost:8080

### Create user 1
# @name createUser1
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "email": "mloneusk@example.co",
  "password": "mloneusk@example.co"
}


### Create user 2
# @name createUser2
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "email": "johny@mail.dev",
  "password": "johny@mail.dev"
}


### Login User 2
# @name createUser2
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "email": "johny@mail.dev",
  "password": "johny@mail.dev",
  "expires_in_seconds": 5
}

### Create chirp (authenticated)
# @name chirp1
POST {{baseUrl}}/api/chirps
Content-Type: application/json
Authorization: Bearer {{createUser2.response.body.token}}

{
  "body": "Hello from testing.http 🚀"
}

### Create chirp (not authenticated)
# @name chirp2
POST {{baseUrl}}/api/chirps
Content-Type: application/json
Authorization: Bearer 5432903210

{
  "body": "Hello from testing.http 🚀"
}

### Get all chirps
GET {{baseUrl}}/api/chirps
Accept: application/json

### Get one chirp
GET {{baseUrl}}/api/chirps/{{chirp1.response.body.id}}
Accept: application/json

### Query Test
GET {{baseUrl}}/api/chirps?sort=desc&author_id=58a6d40a-7db2-4eef-88d5-fe1541f2b972
Accept: application/json